
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 30;
  public static final int SEMI = 36;
  public static final int LPAREN = 32;
  public static final int REPEAT = 8;
  public static final int INT = 2;
  public static final int FOR = 12;
  public static final int MINUS = 28;
  public static final int WRITE = 11;
  public static final int RPAREN = 33;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int LT = 19;
  public static final int OR = 25;
  public static final int BOOL = 3;
  public static final int UNTIL = 9;
  public static final int GEQ = 23;
  public static final int NUM = 16;
  public static final int PLUS = 27;
  public static final int ASSIGN = 17;
  public static final int IF = 4;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 31;
  public static final int NEQ = 20;
  public static final int EQ = 18;
  public static final int TIMES = 29;
  public static final int ELSE = 6;
  public static final int READ = 10;
  public static final int TO = 13;
  public static final int THEN = 5;
  public static final int RCORCHE = 35;
  public static final int LEQ = 21;
  public static final int LCORCHE = 34;
  public static final int END = 7;
  public static final int GT = 22;
  public static final int DO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOL",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "FOR",
  "TO",
  "DO",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "NEQ",
  "LEQ",
  "GT",
  "GEQ",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LCORCHE",
  "RCORCHE",
  "SEMI"
  };
}

